#!/bin/bash
echo "Starting script"
VAR1="Hello"
VAR2="World"
echo "VAR1 is: $VAR1"
echo "VAR2 is: $VAR2"
echo "Concatenating variables..."
result="$VAR1 $VAR2"
echo "Result is: $result"
echo "Exiting script"
